DQN-baseline
pylixir-team/pylixir pull request #22
Opened 2023-07-07 15:32 UTC by Hyeonmin-Kim

Created DQN baseline model with sb3.

평가 스크립트는 train.py의 `evaluate_model` 함수에 있으니 확인 부탁드립니다!
```log
model envs:
('batch_size', 32)
('tau', 0.5)
('gamma', 0.99)
('train_freq', 4)
('policy_kwargs', {'activation_fn': <class 'torch.nn.modules.activation.ReLU'>, 'net_arch': [128, 128]})
Logging to log/logs/DQN_2__logs
DQNPolicy(
  (q_net): QNetwork(
    (features_extractor): FlattenExtractor(
      (flatten): Flatten(start_dim=1, end_dim=-1)
    )
    (q_net): Sequential(
      (0): Linear(in_features=2678, out_features=128, bias=True)
      (1): ReLU()
      (2): Linear(in_features=128, out_features=128, bias=True)
      (3): ReLU()
      (4): Linear(in_features=128, out_features=15, bias=True)
    )
  )
  (q_net_target): QNetwork(
    (features_extractor): FlattenExtractor(
      (flatten): Flatten(start_dim=1, end_dim=-1)
    )
    (q_net): Sequential(
      (0): Linear(in_features=2678, out_features=128, bias=True)
      (1): ReLU()
      (2): Linear(in_features=128, out_features=128, bias=True)
      (3): ReLU()
      (4): Linear(in_features=128, out_features=15, bias=True)
    )
  )
)

average episode length :  12.3427
mean of average reward of each episode :  0.7659769069819148
success rate (%) :  8.799999999999999
```

2023-07-07 23:28 UTC, Hyeonmin-Kim commented on pylixir/envs/PylixirEnv.py
> +        )
이 부분 observation.py에서 확인해보니까 봉인되지 않은 것들 중 가장 큰 두 개의 합이 14를 넘는지 여부를 boolean으로 보내주고 있는 것 같은데 확인 부탁드립니다!

2023-07-08 16:05 UTC, oleneyl requested changes

2023-07-08 16:05 UTC, oleneyl commented on pylixir/envs/PylixirEnv.py
> +            ok = self._client.reroll()
suggestion: action == 15로 하고 16 이상일 때exception을 주는건 어떤가요?

2023-07-09 06:45 UTC, MilkClouds commented on pylixir/envs/PylixirEnv.py
> +        )
self._client가 initialization에 필요하기 때문인데, 아예 __init__에서 client를 미리 만들어두겠습니다.

2023-07-09 06:52 UTC, MilkClouds commented on pylixir/envs/PylixirEnv.py
> +            ok = self._client.reroll()
==15 로만 둬도 self._embedding_provider.action_index_to_action에서 예외가 나오는 형태라 괜찮을 듯 싶습니다.

2023-07-09 06:54 UTC, MilkClouds commented on pylixir/envs/PylixirEnv.py
> +                pickle.dump(self, f)
question: 오류 날 때 덤프 뜨거나 자세한 정보를 출력하는 게 필요하긴 한데 그럼 어떻게 하는 게 좋을까요?

2023-07-10 11:03 UTC, oleneyl commented on pylixir/envs/PylixirEnv.py
> +                pickle.dump(self, f)
try-except로 예외가 캡쳐되었을때 해당 dump가 동작하는게 좋을것 같아요

2023-07-10 11:22 UTC, oleneyl commented on pylixir/envs/PylixirEnv.py
> +                pickle.dump(self, f)
일단 merge하고 차후에 빼는 쪽으로 하시죠

2023-07-10 11:27 UTC, oleneyl approved these changes

2023-07-10 11:27 UTC, merged

2023-07-10 12:14 UTC, MilkClouds commented on pylixir/envs/PylixirEnv.py
> +                pickle.dump(self, f)
앗.. 왜인지 뻔히 눈을 뜨고도 오류가 났을때만 덤프뜨게 제가 설정했다고 생각했었는데 아니었군요. 차후 수정하겠습니다.